export default {
    locale: {
        startsWith: 'Empezar con',
        contains: 'Contiene',
        notContains: 'No contiene',
        endsWith: 'Termina con',
        equals: 'Igual',
        notEquals: 'No igual',
        noFilter: 'No filtrar',
        lt: 'Menor que',
        lte: 'Menor que o igual a',
        gt: 'Más grande que',
        gte: 'Mayor o igual a',
        dateIs: 'La fecha es',
        dateIsNot: 'La fecha no es',
        dateBefore: 'Fecha anterior',
        dateAfter: 'Fecha posterior',
        clear: 'Limpiar',
        apply: 'Aplicar',
        matchAll: 'Coincidir con todos',
        matchAny: 'Coincidir con alguno',
        addRule: 'Agregar regla',
        removeRule: 'Borra regla',
        accept: 'Sí',
        reject: 'No',
        choose: 'Elige',
        upload: 'Cargar',
        cancel: 'Cancelar',
        completed: 'Completado',
        pending: 'Pendiente',
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
        dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        chooseYear: 'Elegir año',
        chooseMonth: 'Elegir mes',
        chooseDate: 'Elegir fecha',
        prevDecade: 'Decada anterior',
        nextDecade: 'Decada postarior',
        prevYear: 'Año previo',
        nextYear: 'Año siguiente',
        prevMonth: 'Mes previo',
        nextMonth: 'Mes siguiente',
        prevHour: 'Hora previa',
        nextHour: 'Hora siguiente',
        prevMinute: 'Minuto previo',
        nextMinute: 'Minuto siguiente',
        prevSecond: 'Segundo previo',
        nextSecond: 'Segundo siguiente',
        am: 'am',
        pm: 'pm',
        today: 'Hoy',
        weekHeader: 'Semana',
        firstDayOfWeek: 0,
        dateFormat: 'yy/mm/dd',
        weak: 'Débil',
        medium: 'Medio',
        strong: 'Fuerte',
        passwordPrompt: 'Ingresa la contresña',
        searchMessage: '{0} resultados disponibles',
        selectionMessage: '{0} elementos seleccionados',
        emptySelectionMessage: 'Elemento no seleccionado',
        emptySearchMessage: 'No se encontraron resultados',
        emptyMessage: 'Sin opciones disponibles',
        aria: {
            trueLabel: 'Verdadero',
            falseLabel: 'Falso',
            nullLabel: 'No seleccionado',
            star: '1 estrella',
            stars: '{star} estrellas',
            selectAll: 'Todos los elementos seleccionados',
            unselectAll: 'Sin ningún elemento seleccionado',
            close: 'Cerrar',
            previous: 'Anterior',
            next: 'Siguiente',
            navigation: 'Navegación',
            scrollTop: 'Desplazar para arriba',
            moveTop: 'Mover hasta arriba',
            moveUp: 'Mover hacía arriba',
            moveDown: 'Move hacía abajo',
            moveBottom: 'Mover botón',
            moveToTarget: 'Mover al objetivo',
            moveToSource: 'Mover a la fuente',
            moveAllToTarget: 'Mover todo al objetivo',
            moveAllToSource: 'Move todo a la fuente',
            pageLabel: '{page}',
            firstPageLabel: 'Primera página',
            lastPageLabel: 'Última página',
            nextPageLabel: 'Página siguiente',
            prevPageLabel: 'Página previa',
            rowsPerPageLabel: 'Renglones por página',
            previousPageLabel: 'Página previa',
            jumpToPageDropdownLabel: 'Saltar al menú desplegable de página',
            jumpToPageInputLabel: 'Saltar a entrada de página',
            selectRow: 'Renglón Seleccionado',
            unselectRow: 'Renglón no seleccionado',
            expandRow: 'Fila expandida',
            collapseRow: 'Fila colapsada',
            showFilterMenu: 'Mostrar menú de filtro',
            hideFilterMenu: 'Esconder menú de filtro',
            filterOperator: 'Operador de filtro',
            filterConstraint: 'Restricción de filtro',
            editRow: 'Editar renglón',
            saveEdit: 'Guardar edición',
            cancelEdit: 'Cancelar edición',
            listView: 'Vista de lista',
            gridView: 'Vista de la celda',
            slide: 'Diapositiva',
            slideNumber: '{slideNumber}',
            zoomImage: 'Zoom de la imagen',
            zoomIn: 'Más Zoom',
            zoomOut: 'Menos Zoom',
            rotateRight: 'Rotar derecha',
            rotateLeft: 'Rotar izquierda'
        }
    }
}