name: Lint

on: [pull_request]
jobs:
    duster:
        name: Lint and Build

        runs-on: ubuntu-latest

        steps:
          - name: Checkout repo
            uses: actions/checkout@v2

          - name: Setup Node
            uses: actions/setup-node@v1
            with:
              node-version: 16

          - name: Install dependencies
            uses: bahmutov/npm-install@v1

          - name: Lint project
            run: npm run lint

          - name: Build project
            run: npm run build
